development:
  adapter: postgresql
  encoding: unicode
  database: page_creator_development
  pool: 5
  username: nurami
  password: nurami

test:
  adapter: postgresql
  encoding: unicode
  database: page_creator_test
  pool: 5
  username: nurami
  password: nurami